### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by BeCarlo** [RQuispeC/top-dropblock#6]
Hi, I try multiple time to train the code but when application start it send me : "CUDA out of memory, try to allocate...".
I try multiple things to fix this error like reduce batch_size, but nothing working do you have a suggestion to it?

**Comment by Jarelk** [comment]
I have the same issue.

`RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 4.00 GiB total capacity; 2.90 GiB already allocated; 24.28 MiB free; 29.64 MiB cached)`

Very weird to me since the numbers don't even seem to add up. Perhaps the real problem is that I only have a Nvidia 980, and for proper training you need something more heavyweight.

**Comment by BeCarlo** [comment]
This is not my case because I have 2080 x trio.

**Comment by RQuispeC** [comment]
I trained the models with a single Tesla GPU (16gb) and batch size of 64 was fine, I would guess that reducing batch size should make it, consider that given a batch size `N`, the code will sample `k` images per id in each batch, by default `k = 4` so you may want to change that setting `sampler.num_instances` with smaller value and make sure that `N/k >= 3` so there is always a valid triplet during training.

**Comment by BeCarlo** [comment]
I try couple times with your tip, but nothing. Can you send trained models?

**Comment by RQuispeC** [comment]
Trained models added in README.
Please notice that the models may not give the exact results as on the paper because the reported results 
 are an average of running the model 5 times. However, the difference shouldn't be large.
